@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE5NTQzODIxMywiaWF0IjoxNzQxNzAwMzAxLCJleHAiOjE3NDE3MDM5MDF9.94JqmPDF91gMlaD0EYUbybAFgej3kXGsTX6-RkAvwZ4
# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE5NTQzODIxMywiaWF0IjoxNzQxNzkxMTA1LCJleHAiOjE3NDE3OTQ3MDV9.7nlfPDHiOdoUKyLCcBqrXcTmRD24EY07CQXr2aGNxbI


### Get all courses
GET http://localhost:3001/api/courses
Authorization: Bearer {{token}}

### Get course based on search term
GET http://localhost:3001/api/courses?searchTerm=ISYS
Authorization: Bearer {{token}}

### Get course based on search term
GET http://localhost:3001/api/courses?searchTerm=Networking
Authorization: Bearer {{token}}

### Get user data
GET http://localhost:3001/api/user/977781381
Authorization: Bearer {{token}}

### Get user data
GET http://localhost:3001/api/user/195438213
Authorization: Bearer {{token}}

### Get user data (with fake user id)
GET http://localhost:3001/api/user/555555
Authorization: Bearer {{token}}

### Create user
POST http://localhost:3001/api/user
Content-Type: application/json

{

    "first_name": "Jack",
    "last_name": "Pepperson",
    "password": "JackPassword",
    "email": "apple@gmail.com",
    "phone_number": 123,
    "is_admin": false,
    "address": {
        "street": "22 Hauptstraße",
        "city": "Berlin",
        "state": "",
        "country": "DEU"
    }
}

### Create user
POST http://localhost:3001/api/user
Content-Type: application/json

{

    "first_name": "Aria",
    "last_name": "Nakamura",
    "password": "AriaPassword",
    "email": "awesome@gmail.com",
    "phone_number": 12343211234,
    "is_admin": true,
    "address": {
        "street": "123 Evergreen Lane",
        "city": "Brookfield",
        "state": "NY",
        "country": "USA"
    }
}

### Create user
POST http://localhost:3001/api/user
Content-Type: application/json

{

    "first_name": "Kelly",
    "last_name": "Lake",
    "password": "KellyPassword",
    "email": "kelly@gmail.com",
    "phone_number": 45,
    "is_admin": false,
    "address": {
        "street": "200 S 500 E",
        "city": "Nowhere",
        "state": "CA",
        "country": "USA"
    }
}

### Edit user
PUT http://localhost:3001/api/user/243582957
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "first_name": "Test Test",
    "last_name": "Test Test Test",
    "email": "123@gmail.com",
    "phone_number": "404",
    "is_admin": true
}

### Login
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "user_id": 195438213,
    "password": "AriaPassword"
}

# ###
# GET http://localhost:3001/api/auth/verify
# Authorization: Bearer {{token}}
# Content-Type: application/json