# Expired token
# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE5NTQzODIxMywiaWF0IjoxNzQxNzAwMzAxLCJleHAiOjE3NDE3MDM5MDF9.94JqmPDF91gMlaD0EYUbybAFgej3kXGsTX6-RkAvwZ4
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE5NTQzODIxMywiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzQyMjIxNjAzLCJleHAiOjE3NDIyMjUyMDN9.LcPcH4arAj6M9vdz14__oWHPwyxDg6UpsPaPcb7naDw


### Get all courses
GET http://localhost:3001/api/courses
Authorization: Bearer {{token}}

### Get course based on search term
GET http://localhost:3001/api/courses?searchTerm=ISYS
Authorization: Bearer {{token}}

### Get course based on search term
GET http://localhost:3001/api/courses?searchTerm=Networking
Authorization: Bearer {{token}}

### Create course
POST http://localhost:3001/api/courses
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "course_id": "ARTS-2001",
    "title": "Modern Art History",
    "description": "A comprehensive overview of art movements from the 20th century, focusing on surrealism, abstraction, and postmodernism.",
    "schedule": "TTH 11-12",
    "classroom_number": "LAB-3233",
    "maximum_capacity": 5,
    "credit_hours": 3,
    "tuition_cost": 800
}

### Edit course
PUT http://localhost:3001/api/courses/ARTS-2001
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "classroom_number": "LAB-4040",
    "maximum_capacity": 50
}

### Get user data
GET http://localhost:3001/api/users/148537402
Authorization: Bearer {{token}}

### Get user data
GET http://localhost:3001/api/users/195438213
Authorization: Bearer {{token}}

### Get user data (with fake user id)
GET http://localhost:3001/api/users/555555
Authorization: Bearer {{token}}

### Search for user
GET http://localhost:3001/api/users?searchTerm=John Jefferson
Authorization: Bearer {{token}}

### Create user
POST http://localhost:3001/api/users
Authorization: Bearer {{token}}
Content-Type: application/json

{

    "first_name": "Jacky",
    "last_name": "Low",
    "password": "JackyPassword",
    "email": "something@gmail.com",
    "phone_number": 452058,
    "is_admin": false,
    "address": {
        "street": "64 Hauptstraße",
        "city": "Berlin",
        "state": null,
        "country": "DEU"
    }
}

### Create user
POST http://localhost:3001/api/users
Content-Type: application/json

{

    "first_name": "Aria",
    "last_name": "Nakamura",
    "password": "AriaPassword",
    "email": "awesome@gmail.com",
    "phone_number": 12343211234,
    "is_admin": true,
    "address": {
        "street": "123 Evergreen Lane",
        "city": "Brookfield",
        "state": "NY",
        "country": "USA"
    }
}

### Create user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "first_name": "Kelly",
    "last_name": "Lake",
    "password": "KellyPassword",
    "email": "kelly@gmail.com",
    "phone_number": 45,
    "is_admin": false,
    "address": {
        "street": "200 S 500 E",
        "city": "Nowhere",
        "state": "CA",
        "country": "USA"
    }
}

### Edit user
PUT http://localhost:3001/api/users/790263736
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "last_name": "Jefferson"
}

### Edit user
PUT http://localhost:3001/api/users/846150586
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "email": "thebestemailever@gmail.com"
}

### Delete user
DELETE http://localhost:3001/api/users/501694971
Authorization: Bearer {{token}}

### Login
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
    "user_id": 195438213,
    "password": "AriaPassword"
}

### Login
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
    "user_id": 98,
    "password": "JohnPassword"
}

### Verify token
GET http://localhost:3001/api/verify-token
Authorization: Bearer {{token}}


### See courses for user:
GET http://localhost:3001/api/enrollment/user/98
Authorization: Bearer {{token}}

### See users for course:
GET http://localhost:3001/api/enrollment/course/CHEM-1001
Authorization: Bearer {{token}}

### See users for course:
GET http://localhost:3001/api/enrollment/course/ARTS-2001
Authorization: Bearer {{token}}


### Enroll in course
POST http://localhost:3001/api/enrollment/enroll
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "user_id": 148537402,
    "course_id": "CHEM-1001"
}

### Enroll in course
POST http://localhost:3001/api/enrollment/enroll
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "user_id": 98,
    "course_id": "ARTS-2001"
}

### Drop course
DELETE http://localhost:3001/api/enrollment/drop
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "user_id": 195438213,
    "course_id": "CHEM-1001"
}

### Drop course
DELETE http://localhost:3001/api/enrollment/drop
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "user_id": 98,
    "course_id": "CSCI-2013"
}

### Test endpoint
GET http://localhost:3001/test