# Expired token
# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE5NTQzODIxMywiaWF0IjoxNzQxNzAwMzAxLCJleHAiOjE3NDE3MDM5MDF9.94JqmPDF91gMlaD0EYUbybAFgej3kXGsTX6-RkAvwZ4
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE5NTQzODIxMywiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzQyMjQxNzU1LCJleHAiOjE3NDIyNDUzNTV9.GaWq5Jsyv1X9qmAPk56FWqkkZytaWO7wWmaRfd_5mik


### Get all courses
GET http://localhost:3001/api/courses
Authorization: Bearer {{token}}

### Get course based on search term
GET http://localhost:3001/api/courses?searchTerm=ISYS
Authorization: Bearer {{token}}

### Get course based on search term
GET http://localhost:3001/api/courses?searchTerm=Networking
Authorization: Bearer {{token}}

### Create course
POST http://localhost:3001/api/course
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "course_id": "ARTS-2001",
    "title": "Modern Art History",
    "description": "A comprehensive overview of art movements from the 20th century, focusing on surrealism, abstraction, and postmodernism.",
    "schedule": "TTH 11-12",
    "classroom_number": "LAB-3233",
    "maximum_capacity": 5,
    "credit_hours": 3,
    "tuition_cost": 800
}

### Create course
POST http://localhost:3001/api/course
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "course_id": "QUAN-1001",
    "title": "Introduction to Quantum Mechanics",
    "description": "A foundational course exploring the principles of quantum physics, including wave-particle duality and quantum entanglement.",
    "maximum_capacity": 30,
    "credit_hours": 4,
    "tuition_cost": 1500
}

### Edit course
PUT http://localhost:3001/api/courses/CHEM-1001
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "description": "This is an introductory course that covers the fundamental concepts and principles of chemistry. It provides a foundation for understanding the structure, properties, and behaviors of matter."
}

### Delete course
DELETE http://localhost:3001/api/course/ARTS-2001
Authorization: Bearer {{token}}
Content-Type: application/json




### Get user data
GET http://localhost:3001/api/users/148537402
Authorization: Bearer {{token}}

### Get user data
GET http://localhost:3001/api/users/195438213
Authorization: Bearer {{token}}

### Get user data (with fake user id)
GET http://localhost:3001/api/users/555555
Authorization: Bearer {{token}}

### Search for user
GET http://localhost:3001/api/users
Authorization: Bearer {{token}}

### Create user
POST http://localhost:3001/api/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "first_name": "Sally",
    "last_name": "Low",
    "password": "SallyPassword",
    "email": "xyz@gmail.com",
    "phone_number": "144",
    "is_admin": false,
    "address": {
        "street": "64 Hauptstraße",
        "city": "Berlin",
        "state": null,
        "country": "DEU"
    }
}

### Create user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "first_name": "Aria",
    "last_name": "Nakamura",
    "password": "AriaPassword",
    "email": "awesome@gmail.com",
    "phone_number": 12343211234,
    "is_admin": true,
    "address": {
        "street": "123 Evergreen Lane",
        "city": "Brookfield",
        "state": "NY",
        "country": "USA"
    }
}

### Create user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "first_name": "Kelly",
    "last_name": "Lake",
    "password": "KellyPassword",
    "email": "kelly@gmail.com",
    "phone_number": 45,
    "is_admin": false,
    "address": {
        "street": "200 S 500 E",
        "city": "Nowhere",
        "state": "CA",
        "country": "USA"
    }
}

### Edit user
PUT http://localhost:3001/api/users/790263736
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "phone": "505404303"
}

### Edit user
PUT http://localhost:3001/api/users/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "phone_number": 4
}

### Delete user
DELETE http://localhost:3001/api/users/690355948
Authorization: Bearer {{token}}

### Login
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
    "user_id": 195438213,
    "password": "AriaPassword"
}

### Login
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
    "user_id": 98,
    "password": "JohnPassword"
}

### Login
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
    "user_id": 2,
    "password": "WilliamPassword"
}

### Verify token
GET http://localhost:3001/api/verify-token
Authorization: Bearer {{token}}


### See courses for user:
GET http://localhost:3001/api/enrollment/user/98
Authorization: Bearer {{token}}

### See users for course:
GET http://localhost:3001/api/enrollment/course/CSCI-1001
Authorization: Bearer {{token}}

### See users for course:
GET http://localhost:3001/api/enrollment/course/ARTS-2001
Authorization: Bearer {{token}}


### Enroll in course
POST http://localhost:3001/api/enrollment/enroll
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "user_id": 148537402,
    "course_id": "CHEM-1001"
}

### Enroll in course
POST http://localhost:3001/api/enrollment/enroll
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "user_id": 98,
    "course_id": "ARTS-2001"
}

### Drop course
DELETE http://localhost:3001/api/enrollment/drop
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "user_id": 195438213,
    "course_id": "CHEM-1001"
}

### Drop course
DELETE http://localhost:3001/api/enrollment/drop
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "user_id": 98,
    "course_id": "CSCI-2013"
}

### Test endpoint
GET http://localhost:3001/test